version: '3.3'

services:
  web:
    build:
      context: "."
    env_file:
      - ".env"
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"  # Mapeia o diretório atual para o diretório /app no container
    depends_on:
      - db

  db:
    image: "sqlite"
    volumes:
      - "./db/sqlite:/app/db/sqlite"
