# fly.toml app configuration file generated for capyba-desafio-autumn-moon-9335 on 2024-09-18T17:43:15-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'capyba-desafio-autumn-moon-9335'
primary_region = 'gig'
console_command = '/rails/bin/rails console'

[build]
  prestart = 'bin/rails db:migrate'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/public'
  url_prefix = '/'
